### ISSUE TITLE
The color picker color does not update when I edit rgba or hexadecimal

### ISSUE THREAD

**Issue by marseillx3** [themesanytime/colorpicker#1]
Hello,

I have a problem with this ColorPicker,
The colorpicker color does not update when I edit rgba code or hexadecimal code : 

![image](https://user-images.githubusercontent.com/32366875/60954961-31107380-a300-11e9-9c3b-f00e0471d92b.png)

Here I selected red with rgba but colorpicker continues to show green.

Do you have an idea to solve this problem?

Thank you for your help

**Comment by spvcoder** [comment]
Hello, it will be fixed in 2 days.

**Comment by spvcoder** [comment]
fixed
